### ISSUE TITLE
[Suggestion] messages.yml

### ISSUE THREAD

**Issue by BroCrows** [doge-pm/DogeWorlds#1]
Could you add a messages.yml for 90% of the messages!

**Comment by cooldogedev** [comment]
You can create your own language file and use it in the [config](https://github.com/doge-pm/DogeWorlds/blob/main/resources/config.yml#L7) see [Example](https://github.com/doge-pm/DogeWorlds/blob/main/resources/en-US.json).

**Comment by cooldogedev** [comment]
You can leave a star if you want to support the project.

**Comment by BroCrows** [comment]
I am sorry for my blindness
